### PR TITLE
Bugfix in crZ control region

### PR DESCRIPTION
**Pull request by sscruz**
Fixing bug in the Z control region. Currently no ee events are entering in the selection because there's a veto on the Z mass for ee events. This PR removes the veto from that region

### CODE REVIEW

**Review by bryates — COMMENTED** [review]
Thanks @sscruz. Can you update all the reference files for the CI?

**Comment by sscruz** [comment]
sorry for the wait, now it's done

**Comment by bryates** [comment]
> sorry for the wait, now it's done

Thanks! Once the CI finishes, I'll merge this PR.

**Comment by kmohrman** [comment]
Looks good to me as well. Once the CI finishes I'd be happy for it to be merged.

**Pull request merged**
