### PR TITLE
Fix fakes in datacard maker

### PR DESCRIPTION
**Pull request by bryates**
This PR fixes the issue with the fakes. The recent updates was overwriting each year entry with the subsequent (e.g., if loading `nonpromptUL17` followed by `nonpromptUL18` _only_ `nonpromptUL18` would be written to the datacard). It's a bit of a hack, since it treats the fakes as special, but we can come back to this later if we need to generalize it.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks @bryates. I'm currently testing this (as discussed on mattermost), but in the meantime I have a quick question. I'm wondering why the nonprompts have to be treated differently from the other samples to begin with (as you mentioned they are being treated as a special case)?

**Comment by bryates** [comment]
> Thanks @bryates. I'm currently testing this (as discussed on mattermost), but in the meantime I have a quick question. I'm wondering why the nonprompts have to be treated differently from the other samples to begin with (as you mentioned they are being treated as a special case)?

I think it's because we're classifying the fakes as background, whereas the other systematics are applied to the signal. The way the datacard maker merges the signals by year is different. We _could_  just lump the fakes into signal, and make sure when we get to `signalcount` and `bkgcount` we give it the right number.

**Comment by kmohrman** [comment]
> > Thanks @bryates. I'm currently testing this (as discussed on mattermost), but in the meantime I have a quick question. I'm wondering why the nonprompts have to be treated differently from the other samples to begin with (as you mentioned they are being treated as a special case)?
> 
> I think it's because we're classifying the fakes as background, whereas the other systematics are applied to the signal. The way the datacard maker merges the signals by year is different. We _could_ just lump the fakes into signal, and make sure when we get to `signalcount` and `bkgcount` we give it the right number.

Oh, interesting, I did not realize this. Just to make sure I'm following, you are saying the systematics are not applied to the backgrounds (just to signal)?

**Comment by bryates** [comment]
> > > Thanks @bryates. I'm currently testing this (as discussed on mattermost), but in the meantime I have a quick question. I'm wondering why the nonprompts have to be treated differently from the other samples to begin with (as you mentioned they are being treated as a special case)?
> > 
> > 
> > I think it's because we're classifying the fakes as background, whereas the other systematics are applied to the signal. The way the datacard maker merges the signals by year is different. We _could_ just lump the fakes into signal, and make sure when we get to `signalcount` and `bkgcount` we give it the right number.
> 
> Oh, interesting, I did not realize this. Just to make sure I'm following, you are saying the systematics are not applied to the backgrounds (just to signal)?

Yes, which I guess we need to decide if that is correct. Here's an example from a root file I have:
```
root [3] gDirectory->ls("*sm*btagSFbc_2016Up")
TFile**         histos/ttx_multileptons-2lss_m_2b.root
 TFile*         histos/ttx_multileptons-2lss_m_2b.root
  KEY: TH1D     tHq_sm_btagSFbc_2016Up;1        Events
  KEY: TH1D     tllq_sm_btagSFbc_2016Up;1       Events
  KEY: TH1D     ttH_sm_btagSFbc_2016Up;1        Events
  KEY: TH1D     ttll_sm_btagSFbc_2016Up;1       Events
  KEY: TH1D     ttlnu_sm_btagSFbc_2016Up;1      Events
  KEY: TH1D     tttt_sm_btagSFbc_2016Up;1       Events
```

**Comment by kmohrman** [comment]
Thanks @bryates! I'd be happy for this to be merged as soon as the CI finishes.

**Pull request merged**
