### PR TITLE
Update json files

### PR DESCRIPTION
**Pull request by bryates**
This PR adds better handling of the extension (`ext`) files. Since these are additional statistics to be added the the main samples, they must be in the main json file. I've added a script to merge them together, and adjust `nEvents`, `nGenEvents`, and `nSumOfWeights`.

I've also updated some of the old `nanoAODv8` samples to `v9` as mentioned in issue #87, but there are still a few that do not exist yet.

### CODE REVIEW

**Comment by bryates** [comment]
@Andrew42 I didn't redo any of the PSI samples. Are you still using those, or are you focusing on the skims instead?

**Comment by Andrew42** [comment]
> @Andrew42 I didn't redo any of the PSI samples. Are you still using those, or are you focusing on the skims instead?

I've never used the PSI samples. I'm pretty sure those are only used by @sscruz, since we have trouble accessing those files. However, since this is modifying samples that the skims are based on I will probably want to merge in these changes to PR #129 before that PR gets merged into master.

We might also want to think of some mechanism to keep the 'skim' and 'original' json files synchronized. As it is now the skims have their own copy of the `nSumOfWeights` which is probably a good thing since that value _should_ correspond to w/e files were used to make the skim at the time of creation.

**Comment by kmohrman** [comment]
Thanks @bryates! Just wondering if you could explain a bit more about the change for the `ext` samples. I'm not sure if I understand why we need to merge them together at the JSON level. I think the way we were handling it before, we just specified the same name for the sample axis in the histogram, so all of the events will end up in the same histogram. I'm wondering what is incorrect about that approach we were using before?

**Comment by bryates** [comment]
> Thanks @bryates! Just wondering if you could explain a bit more about the change for the `ext` samples. I'm not sure if I understand why we need to merge them together at the JSON level. I think the way we were handling it before, we just specified the same name for the sample axis in the histogram, so all of the events will end up in the same histogram. I'm wondering what is incorrect about that approach we were using before?

I don't think that's enough, because each event is weighted by `1/sumWeights`, so the `ext` samples will have a different weight than the standard samples. This means the low stats is weighted by a larger weight (`1/ smaller sumWeights`). We should be treating them as one set with the same weights.

**Comment by kmohrman** [comment]
> > Thanks @bryates! Just wondering if you could explain a bit more about the change for the `ext` samples. I'm not sure if I understand why we need to merge them together at the JSON level. I think the way we were handling it before, we just specified the same name for the sample axis in the histogram, so all of the events will end up in the same histogram. I'm wondering what is incorrect about that approach we were using before?
> 
> I don't think that's enough, because each event is weighted by `1/sumWeights`, so the `ext` samples will have a different weight than the standard samples. This means the low stats is weighted by a larger weight (`1/ smaller sumWeights`). We should be treating them as one set with the same weights.

But, each `sum of weights` is specific to each MC sample. If the regular and ext samples are from different MC samples, then I'm not sure if I understand why it makes sense to essentially average their sum of weights (and use that average for all events from both samples), but maybe I'm just thinking about this in the wrong way. Maybe @Andrew42 could also comment?

**Comment by bryates** [comment]
> > > Thanks @bryates! Just wondering if you could explain a bit more about the change for the `ext` samples. I'm not sure if I understand why we need to merge them together at the JSON level. I think the way we were handling it before, we just specified the same name for the sample axis in the histogram, so all of the events will end up in the same histogram. I'm wondering what is incorrect about that approach we were using before?
> > 
> > 
> > I don't think that's enough, because each event is weighted by `1/sumWeights`, so the `ext` samples will have a different weight than the standard samples. This means the low stats is weighted by a larger weight (`1/ smaller sumWeights`). We should be treating them as one set with the same weights.
> 
> But, each `sum of weights` is specific to each MC sample. If the regular and ext samples are from different MC samples, then I'm not sure if I understand why it makes sense to essentially average their sum of weights (and use that average for all events from both samples), but maybe I'm just thinking about this in the wrong way. Maybe @Andrew42 could also comment?

The nominal and ext should be thought of as one giant sample. If we scale the nominal by `xsec/sumNominalWeights` and the ext by `xsec/sumExtWeights` then we'll essentially have twice the predicted yield, and still be sensitive to the fluctuations in the low statistics nominal sample. By combining them into one sample, we smooth things out.

**Comment by bryates** [comment]
The CR plots look good to me.
http://www.crc.nd.edu/~byates2/coffea/update_bkg_20211123_1319/

**Comment by kmohrman** [comment]
The PR looks good to me. And thanks for explaining about the sum of weights for the `ext samples`.

**Review by kmohrman — APPROVED** [review]

**Review by Andrew42 — APPROVED** [review]
I'm also fine with these changes

**Comment by kmohrman** [comment]
@bryates do you want me to merge this, or were you planning to?

**Comment by bryates** [comment]
> @bryates do you want me to merge this, or were you planning to?

I'll do it now.

**Pull request merged**
