### PR TITLE
EGM photon SFs

### PR DESCRIPTION
**Pull request by bryates**
This PR adds the medium photon ID SFs from the EGM POG found on the [Twiki](https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018).

### CODE REVIEW

**Comment by bryates** [comment]
@kmohrman @sscruz @Andrew42 did any of you have comments on this PR? I'm just adding the photon SF files, so it shouldn't affect anything else.

**Comment by kmohrman** [comment]
Thanks for the PR, and sorry for my delayed response. Just so I can understand the context a bit more, what's the purpose for adding them? Also could you add a readme that documents exactly where they were copied from?

**Comment by bryates** [comment]
> Thanks for the PR, and sorry for my delayed response. Just so I can understand the context a bit more, what's the purpose for adding them? Also could you add a readme that documents exactly where they were copied from?

We're working on adding the ttgamma process, so we'll need these SFs for that signal region. I figured since we have all the other SFs stored in TopCoffea, I'd put them here. I'll add a README explaining where they came from.

**Comment by bryates** [comment]
> > Thanks for the PR, and sorry for my delayed response. Just so I can understand the context a bit more, what's the purpose for adding them? Also could you add a readme that documents exactly where they were copied from?
> 
> We're working on adding the ttgamma process, so we'll need these SFs for that signal region. I figured since we have all the other SFs stored in TopCoffea, I'd put them here. I'll add a README explaining where they came from.

@kmohrman the README is now in place
https://github.com/TopEFT/topcoffea/tree/photonSFs/topcoffea/data/photonSF#readme
Let me know if anything is unclear.

**Comment by bryates** [comment]
@kmohrman I made one last change. Since we use the `coffea` tools to load the SFs, we need to also store the errors (unless anyone knows how to get those from the tools). I simply added error histograms to the SF root files, which come from the bin errors on the EGM POG provided files. I've updated the README, and added the relevant script.

**Comment by kmohrman** [comment]
Wondering if you could say a bit more about the context for the purpose of having the errors stored separately like this? And what do the errors correspond to (just like stat error)? Or are you referring to some kind of up/down systematic variations recommended by the POG?

**Comment by bryates** [comment]
> Wondering if you could say a bit more about the context for the purpose of having the errors stored separately like this? And what do the errors correspond to (just like stat error)? Or are you referring to some kind of up/down systematic variations recommended by the POG?

The contact wasn't clear on what the errors correspond to, he just stated we should use the bin errors in `EGamma_SF2D`.
As for storing the errors, I don't know of a way to ask for them using the coffea evaluator tools
https://github.com/TopEFT/topeft/blob/047aad7774b7136b4d3666535d0f5d7afac3a4fc/topeft/modules/corrections.py#L433-L434.
Our lepton SFs have separate histograms for the errors
https://github.com/TopEFT/topeft/blob/047aad7774b7136b4d3666535d0f5d7afac3a4fc/topeft/modules/corrections.py#L53
but I'm not sure if we added these, or if the POG included them by default.

**Comment by kmohrman** [comment]
Ok. I guess it might be good to follow up with the contact to make sure it's understood as to what the errors correspond to and if what you're doing matches what he was suggesting. 

Anyway if you are grabbing the `.variances()` from the bins, do you have to sqrt to get the error?

**Comment by bryates** [comment]
> Ok. I guess it might be good to follow up with the contact to make sure it's understood as to what the errors correspond to and if what you're doing matches what he was suggesting.
> 
> Anyway if you are grabbing the `.variances()` from the bins, do you have to sqrt to get the error?

Yes, what I'm doing matches what he suggested (shifting the SFs by the errors). Would you like me to follow up on what went into computing those? Thanks for catching the bug using `variance()`. If I had passed it to another histogram as a variance, it would have been fine, but using it as bin values requires `sqrt`.

**Comment by kmohrman** [comment]
Ok if this is what the POG suggests then that sounds fine with me.

But yeah if you are going to save the .variances() (and if you need sqrt to get the actual error) then I would maybe name them `var` instead of `err` (so that people know they still need to take sqrt) or just directly save the sqrt.

**Comment by bryates** [comment]
> Ok if this is what the POG suggests then that sounds fine with me.
> 
> But yeah if you are going to save the .variances() (and if you need sqrt to get the actual error) then I would maybe name them `var` instead of `err` (so that people know they still need to take sqrt) or just directly save the sqrt.

I updated the script and root files to store the error instead of the variance.
https://github.com/TopEFT/topcoffea/blob/69bb9a9606b077219b0c757af3d4043cef4fb030/topcoffea/data/photonSF/add_err.py#L12

**Comment by kmohrman** [comment]
Ok. It's fine with me if you want to merge it now.

**Comment by bryates** [comment]
Just to document this, the TOP EGM contact replied that the bin uncertainties are indeed the quad sum of `altBkgModel`, `altSignalModel`, `altMCEff`, `altTagSelection`, `statData`, and `statMC`.

**Comment by kmohrman** [comment]
Ok, just the quad sum (i.e. without the sqrt already applied)?

**Comment by bryates** [comment]
> Ok, just the quad sum (i.e. without the sqrt already applied)?

The bin errors would be `sqrt(altBkgModel^2 + altSignalModel^2 + ...)`, but under the hood the variances are stored, so we have to use `sqrt(variance())` to get the correct error value.

**Pull request merged**
