### PR TITLE
Optimize JSON making code and include data JSONs

### PR DESCRIPTION
**Pull request by Andrew42**
This PR implements an optimization in the way the data files are queried from DAS. Previously in order to get a count of the total number of events the code would try to access and open each file and extract the relevant information. However, this is unnecessary as DAS can just provide us with this info directly (at least for data).

To that end, I've modified the [createJson.py](https://github.com/TopEFT/topcoffea/blob/optimize-json-maker/topcoffea/modules/createJSON.py) script to attempt to determine if the DAS query is for actual data and if so run the query to get the total number of events directly from DAS instead of from the files.

My fix here is rather limited in scope as it should only take effect when all of the following are true: The information is coming from DAS, the target datasets are real data, and the requested number of files is the full dataset. If any of those criteria are not met then it falls back to the previous method for determining the event counts. The way I implemented these changes is a bit crude, but I did it this way so as to avoid making edits to the lower level code that is defined in [DASsearch.py](https://github.com/TopEFT/topcoffea/blob/optimize-json-maker/topcoffea/modules/DASsearch.py).

I've also taken the liberty of implementing the json making queries into [make_jsons.py](https://github.com/TopEFT/topcoffea/blob/optimize-json-maker/analysis/topEFT/make_jsons.py), for all three data taking years. I decided to place these json files in their own sub-directory called 'data_samples', which is then further subdivided by run year. A given dataset will itself be called something like:

`DatasetName_ERA-ULYEAR.json`

It should be noted that the 2016 datasets have some rather unusual era names, which is due to the whole APV issue and is explained on the corresponding twiki page [here](https://twiki.cern.ch/twiki/bin/view/CMS/PdmVDatasetsUL2016).

Lastly, I've also gone ahead and committed the results of running the `make_jsons.py` script in order to get us going with a basic starting point. I defined the datasets inside of `make_jsons.py` in such a way that it should be fairly straightforward to modify things should we find out that we need to switch to a different version of NANOAOD.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks very much @Andrew42 for this PR. It looks good to me. I think the only thing I'd request before we merge is if you could add a data samples cfg to `topcoffea/cfg/` so that we can easily process these samples.

**Comment by bryates** [comment]
Thanks @Andrew42 for making this PR. Have you or @yanfr0818 had a chance to run all the data through the control regions? And should we consider making something similar to @kmohrman's `ref_yields.json` for the data? Maybe rename hers to `ref_yields_MC.json` and make a new one for the data as `ref_yields_Data.json`?

**Comment by Andrew42** [comment]
I've added a cfg file for the data samples. I also noticed that a few datasets seem to be missing, which I tracked down to them being marked as "INVALID" on DAS. These invalid datasets don't appear to have any associated files that we can search for on DAS, so for now we will just need to run without them, but we should keep an eye out for if this gets resolved, e.g. by checking on the [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRun2LegacyAnalysis). The missing datasets are:

SingleElectron_E-UL2017
SingleMuon_E-UL2017
SingleMuon_D-UL2017
DoubleMuon_B-UL2018

I've added a comment about each of these missing datasets in the `make_jsons.py` file.

> Thanks @Andrew42 for making this PR. Have you or @yanfr0818 had a chance to run all the data through the control regions? And should we consider making something similar to @kmohrman's `ref_yields.json` for the data? Maybe rename hers to `ref_yields_MC.json` and make a new one for the data as `ref_yields_Data.json`?

I plan to hold off on adding a reference yield file for the data samples until we get a more stabilized list of data samples

**Comment by bryates** [comment]
> I've added a cfg file for the data samples. I also noticed that a few datasets seem to be missing, which I tracked down to them being marked as "INVALID" on DAS. These invalid datasets don't appear to have any associated files that we can search for on DAS, so for now we will just need to run without them, but we should keep an eye out for if this gets resolved, e.g. by checking on the [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRun2LegacyAnalysis). The missing datasets are:
> 
> SingleElectron_E-UL2017
> SingleMuon_E-UL2017
> SingleMuon_D-UL2017
> DoubleMuon_B-UL2018
> 
> I've added a comment about each of these missing datasets in the `make_jsons.py` file.
> 
> > Thanks @Andrew42 for making this PR. Have you or @yanfr0818 had a chance to run all the data through the control regions? And should we consider making something similar to @kmohrman's `ref_yields.json` for the data? Maybe rename hers to `ref_yields_MC.json` and make a new one for the data as `ref_yields_Data.json`?
> 
> I plan to hold off on adding a reference yield file for the data samples until we get a more stabilized list of data samples

Ok, sounds good to me.

**Comment by Andrew42** [comment]
There appear to be some inconsistencies with a number of hardcoded lists and dictionaries that causes the code to crash when running over certain datasets from certain years. I think I know the cause of these crashes and will commit a fix shortly, but please don't merge this PR until then.

**Comment by Andrew42** [comment]
Alright, I've pushed the fix and successfully ran over ~1M events from each dataset+era+year combination (using the futures executor). So the code should at least be in a usable state.

No word on the validity of the data samples that are actually being used, but they should at the very least line up with what is recommended on the PdmV twiki pages.

**Comment by kmohrman** [comment]
Thanks @Andrew42. I'm happy to merge the PR at this point, unless anyone else wanted more time to look at it before we proceed with the merge.

**Pull request merged**
