### PR TITLE
Fix ext stats jsons

### PR DESCRIPTION
**Pull request by kmohrman**
This PR fixes bugs in the ext stats jsons introduced in PR #269.

Note that it should *not* be merged until after the skims are created.

@bryates, I'm wondering if you could take a few minutes to carefully look through the changes on this branch, just to make sure that it looks like I have corrected the issues I cased in PR 269?

### CODE REVIEW

**Review by bryates — APPROVED** [review]
Thanks @kmohrman, all the changes look correct to me!

**Comment by Andrew42** [comment]
I've remade the skims and updated the corresponding json files

```
python make_skim_jsons.py --file ND_bkgd_mc_skim_locations.txt --json-dir ../../topcoffea/json/background_samples/central_UL
```

**Comment by kmohrman** [comment]
I've processed these files, and run the resulting pkl file through the data card maker. The njets [templates](https://www.crc.nd.edu/~kmohrman/EFT/TopCoffea/fitting/anatests/anatest08/template_histos/njets/) look reasonable to me. If there are no objections, I will go ahead and merge.

**Comment by bryates** [comment]
> I've processed these files, and run the resulting pkl file through the data card maker. The njets [templates](https://www.crc.nd.edu/~kmohrman/EFT/TopCoffea/fitting/anatests/anatest08/template_histos/njets/) look reasonable to me. If there are no objections, I will go ahead and merge.

Sound good to me.

**Pull request merged**
