### PR TITLE
Dictionary of years per run

### PR DESCRIPTION
**Pull request by bryates**
This PR adds a dictionary of runs and what years they contain. To check if a year is run 2 or run 3, one can do
```python
from topcoffea.modules.get_param_from_jsons import GetParam
from topcoffea.modules.paths import topcoffea_path
run_dict = GetParam(topcoffea_path("params/run_dict.json"))

if year in run_dict('Run3'):
...
```

### CODE REVIEW

**Comment by bryates** [comment]
@kmohrman @Andrew42 @sscruz any comments on this PR? It's pretty minimal.

**Comment by kmohrman** [comment]
I don't have any objections to this in principle. But I'm wondering is there a reason to have a separate json file for it instead of adding it to the params json file?

Also, where is this used? It may be useful to add a helper function where you just pass a year and it gives you a bool. Like the usage would be something like `is_run2(year)` and that would give you True or False or throw an error (it would just check if the year is in the Run 2 list, the Run 3 list, or neither). And similar for `is_run3(year)`.

**Comment by bryates** [comment]
> I don't have any objections to this in principle. But I'm wondering is there a reason to have a separate json file for it instead of adding it to the params json file?
> 
> Also, where is this used? It may be useful to add a helper function where you just pass a year and it gives you a bool. Like the usage would be something like `is_run2(year)` and that would give you True or False or throw an error (it would just check if the year is in the Run 2 list, the Run 3 list, or neither). And similar for `is_run3(year)`.

I guess there's no real reason to keep it in a separate file. I can put these in `params.json`. As for a helper function, I was going back and forth on that, but since you suggested it, I'll add something. I have a PR in TopEFT to use the dictionary
https://github.com/TopEFT/topeft/blob/b97b0382c77133bd20f06e76178b0971289c1420/topeft/modules/corrections.py#L263

**Comment by bryates** [comment]
@kmohrman I've implemented your suggestion to use `run_id`. Are you happy with this PR?

**Comment by kmohrman** [comment]
Looks good. Merge away!

**Pull request merged**
