### PR TITLE
Add correlations to datacards

### PR DESCRIPTION
**Pull request by bryates**
This PR adds the option to specify correlated bins via `self.syst_correlation`.
Example:
```
self.syst_correlation = {'ttH': [['renorm', 'fact', 'renorm_fact', 'pdf_scale'], 'gg'], 
'ttll': [['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale'], 'gg'], 
'ttlnu': [['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale'], 'qq'], 
'tHq': [['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale'], 'qg'], 
'tllq': [['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale'], 'qq'], 
'tttt': [['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale'], 'gg']}
```
will make correlated bins for `gluon-gluon`, `quark-anti-quark`, and `quark-gluon` interactions for the `renormalization/factorization`, `PDF scale`, and `QCD scale` uncertainties. It also adds the option to specify asymmetric uncertainties as a string:
```
self.syst_special = {qcd_scale' : {'ttH': '1.092/1.058', 'tllq': 0.01, 'ttlnu': '1.12/1.13', 
'ttll': '1.12/1.10', 'tHq': '1.08/1.06', 'Diboson': 0.02, 'Triboson': 0.026, 'convs': 0.10}}
```
where e.g. `'ttH': '1.092/1.058'` means `ttH` has a `down` uncertainty of 9.2% and an `up` uncertainty of 5.8%.

The datacard will have entries like:
```
pdf_scale_qg_flat         lnN             -               -               -               -           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037           1.037
qcd_scale_qg_flat         lnN             -               -               -               -             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06             1.08/1.06
```

### CODE REVIEW

**Comment by bryates** [comment]
> hi @bryates thanks a lot for the PR. To me it looks like the code is correct, however I would suggest keeping the same logic for `syst_correlation` and `syst_special`. For `sys_correlation` the keys are the processes while for `syst_special`, the keys are the nuisances. I find the latter to be a bit more user friendly as one usually thinks of a given uncertainty that may affect different processes that you can specify

Thanks @sscruz, I've made these changes:
```diff
-        # {'proc': [[systs], 'name']} will assign all procs a special name for the give systematics
-        # e.g. {'ttH': [['renorm', 'fact'], 'gg']} will add `_gg` to the ttH renorm/fact systemtics
-        self.syst_correlation = {'ttH': [['renorm', 'fact', 'renorm_fact', 'pdf_scale'], 'gg'], 'ttll': [['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale'], 'gg']
+        # {'proc': 'type'} will assign all procs a special name for the give systematics
+        # e.g. {'ttH': 'gg'} will add `_gg` to the ttH  found in `self.syst_correlated`
+        self.syst_correlation = {'ttH': 'gg', 'ttll': 'gg', 'tttt': 'gg', 'tHq': 'qg', 'tllq': 'qq', 'ttlnu': 'qq', 'Diboson': 'qq', 'Triboson': 'qq', 'convs': 'gg'}
+        # List of systematics which require specific correlations
+        # Any systematic _not_ found in this list is assumed to be fully correlated across all processes
+        self.syst_correlated  = ['renorm', 'fact', 'renorm_fact', 'pdf_scale', 'qcd_scale']
```

```diff
-        if correlation in self.syst_correlation and any([s in syst for s in self.syst_correlation[correlation][0]]): # Look for syst process and process process
-            correlation = '_'+self.syst_correlation[correlation][1]
+        syst = syst.replace('Up', '').replace('Down', '')
+        if syst in self.syst_correlated and correlation in self.syst_correlation: # Look for correlated systs and process type
+            correlation = '_'+self.syst_correlation[correlation]
```
so now there's a `master` list of correlated systematics, and a dictionary of processes and what type the map to.

**Comment by kmohrman** [comment]
Hi @bryates, thanks for this PR. Before we move forward with merging, I'm wondering if you were planning to check the impact that these updates have on the limits (or maybe ou already have)? I think one way to check this would be to take a pkl file and make datacards with and without these updates, then run through combine and compare the limits. But of course there are probably other ways of doing the comparison as well.

**Comment by bryates** [comment]
> Hi @bryates, thanks for this PR. Before we move forward with merging, I'm wondering if you were planning to check the impact that these updates have on the limits (or maybe ou already have)? I think one way to check this would be to take a pkl file and make datacards with and without these updates, then run through combine and compare the limits. But of course there are probably other ways of doing the comparison as well.

The differences are small when comparing this branch to the master (without any systematics)
```
FoM (>1 is better)
WC      FoM
`(CI_(.022222.njet.runII.Freeze.Asimov_correlations high) - CI_(.022222.njet.runII.Freeze.Asimov_correlations low)) / (CI_(.022222.njet.runII.Freeze.Asimov_master high) - CI_(.022222.njet.runII.Freeze.Asimov_master low))`
cQq13 1.015
cQq83 1.017
cQq11 1.011
ctq1 1.005
cQq81 1.034
ctq8 1.023
ctt1 1.0
cQQ1 1.0
cQt8 1.0
cQt1 1.0
ctW 1.015
ctZ 1.039
ctp 1.12
cpQM 1.376
ctG 1.116
cbW 1.027
cpQ3 1.029
cptb 1.029
cpt 1.402
cQl3i 1.002
cQlMi 1.005
cQei 1.005
ctli 1.005
ctei 1.005
ctlSi 1.005
ctlTi 1.006
```
image

**Comment by kmohrman** [comment]
Thanks for this check @bryates. Just to clarify one point though, I'm wondering if you could explain a bit more what you mean by "without any systematics"? I know the pkl file was produced without any systematics, but when you ran the data card maker, did you have the systematics turned on? (If not, then probably we'd expect exact agreement, right?)

**Comment by bryates** [comment]
> Thanks for this check @bryates. Just to clarify one point though, I'm wondering if you could explain a bit more what you mean by "without any systematics"? I know the pkl file was produced without any systematics, but when you ran the data card maker, did you have the systematics turned on? (If not, then probably we'd expect exact agreement, right?)

Yes, the datacards from this new branch are run with the systematics flag, so all the flat systematics are included.

**Comment by kmohrman** [comment]
Ok, then assuming @sscruz is happy with your edits to address his comments, then it sounds like it's ready to merge. However, I'm wondering if you might want to merge in the changes from the `master` before merging this PR, just to making sure it passes the CI?

**Comment by bryates** [comment]
> Ok, then assuming @sscruz is happy with your edits to address his comments, then it sounds like it's ready to merge. However, I'm wondering if you might want to merge in the changes from the `master` before merging this PR, just to making sure it passes the CI?

Yes, I was planning on that once `earth` is responding agian.

**Pull request merged**
