### PR TITLE
update env creation to new spec

### PR DESCRIPTION
**Pull request by btovar**
Uses the new poncho_package_run and create to create topcoffea packages.  Also, it ensures that the version of coffea in the package is the same as the local one.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks @btovar for this PR! Sorry for being slow to review it, I just noticed it now (if you want to list me as a reviewer for future PRs, feel free to do that, as I'll get a notification about them and will hopefully respond sooner).

I have a quick question about an error I saw while testing out these changes. I checked out your branch, and attempted to run a quick job (`python work_queue_run.py ../../topcoffea/cfg/check_yields_sample.cfg`), but ended up getting the error pasted below (several lines before the error are included for context). I'm not sure if I'm just making a mistake or missing a step, or if there is some issue. I'm also not sure if the conda version warning is relevant.
```
Creating temporary environment in /tmp/tmpywubdia5
creating conda environment...
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/tmp/tmpywubdia5/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/tmpywubdia5/condaenv.25gebkp4.requirements.txt']
Pip subprocess output:
Collecting coffea==0.7.9
  Using cached coffea-0.7.9-py2.py3-none-any.whl (180 kB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement topcoffea (from versions: none)
ERROR: No matching distribution found for topcoffea

failed

CondaEnvException: Pip failed

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/topcoffea-env1/bin/poncho_package_create", line 156, in <module>
    pack_env(args.spec, args.out)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/topcoffea-env1/bin/poncho_package_create", line 25, in pack_env
    subprocess.check_call(['conda', 'env', 'create', '--prefix', env_dir,
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/topcoffea-env1/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--prefix', '/tmp/tmpywubdia5', '--file', '/tmp/tmpywubdia5/conda_spec.yml']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kmohrman/coffea_dir/check_PRs/btovar_envs/topcoffea/analysis/topEFT/work_queue_run.py", line 179, in <module>
    'environment_file': topeftenv.get_environment(),
  File "/afs/crc.nd.edu/user/k/kmohrman/coffea_dir/check_PRs/btovar_envs/topcoffea/analysis/topEFT/topeftenv.py", line 149, in get_environment
    return _create_env(env_name, force)
  File "/afs/crc.nd.edu/user/k/kmohrman/coffea_dir/check_PRs/btovar_envs/topcoffea/analysis/topEFT/topeftenv.py", line 68, in _create_env
    subprocess.check_call(['poncho_package_create', f.name, env_name])
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/topcoffea-env1/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['poncho_package_create', '/tmp/tmpsp37blcq', 'envs/env_spec_a2aa254c_edit_b3923a66.tar.gz']' returned non-zero exit status 1.
```

**Comment by btovar** [comment]
Strange, I have not seen that before. Let me try to reproduce it.

**Comment by kmohrman** [comment]
Thanks again @btovar for this PR. It seems to be passing the CI, and I've run a test job from my end as well, and it works for me. I also brought it up at our analysis group meeting today, and no one raised any objections, so I'm happy to merge it at this point.

**Comment by btovar** [comment]
sounds good!

**Pull request merged**
