### PR TITLE
Add simplified SF functions

### PR DESCRIPTION
**Pull request by Andrew42**
This PR adds two new functions to [corrections.py](https://github.com/TopEFT/topcoffea/blob/simplify-lepSF/topcoffea/modules/corrections.py#L78-L120), `AttachMuonSF` and `AttachElectronSF`. They aim to replace the `GetLeptonSF` function by simplifying the logic required to apply the event level lepton SF.

The new methods operate by attaching/inserting a new "sub-column" to the array that gets passed to the functions. This sub-column contains the lepton scale factor corresponding to each lepton in that array. Currently, the functions attach three new entries:

`sf_nom`, `sf_hi`, `sf_lo` 

Which correspond to the nominal, up variation, and down variation respectively.

The two new functions take an additional optional argument `year` which defaults to `2018`. This argument controls which SF table to evaluate the corresponding lepton SF.

An example of how to calculate the event level scale factor is given below:
```python
def process(self,events):
    dataset = events.metadata['dataset']
    year = self._samples[dataset]['year']

    e  = events.Electron
    mu = events.Muon

    #####################################
    # Apply your object level cuts here #
    #####################################
    #   ...
    #   ...
    #   ...
    #####################################
    
    AttachElectronSF(e,year=year) # Can now access electron scale factors via: e.sf_nom
    AttachMuonSF(mu,year=year)    # Can now access muon scale factors via: mu.sf_nom

    leps = ak.concatenate([e,mu],axis=-1)
    events['lepSF_nom'] = ak.prod(leps.sf_nom,axis=-1)
    events['lepSF_hi']  = ak.prod(leps.sf_hi,axis=-1)
    events['lepSF_lo']  = ak.prod(leps.sf_lo,axis=-1)

    nLeps  = ak.num(leps)
    events = events[nLeps > 1]
```

You would then be able to apply whatever event selection you want and still have access to the event level lepton SF for the corresponding events you have selected.

I've marked this PR as [WIP] because I've only included the new functions, but haven't gone through and replaced the old `GetLeptonSF` usage in the rest of the code. My reasoning for this is because the old and new implementations take rather different approaches to computing the SF. In the old method you computed the SF _after_ doing the event selection and splitting up your sample into the different lepton categories, for example:
```python
eee =  e[(nElec==3)&(nMuon==0)]
mmm = mu[(nElec==0)&(nMuon==3)]

eee_leps = ak.combinations(eee, 3, fields=["e0", "e1", "e2"])
mmm_leps = ak.combinations(mmm, 3, fields=["m0", "m1", "m2"])

lepSF_eee = GetLeptonSF(eee_leps.e0.pt, eee_leps.e0.eta, 'e', ...)
lepSF_mmm = GetLeptonSF(mmm_leps.m0.pt, mmm_leps.m0.eta, 'm', ...)

```
Then getting the SF for each of these new arrays individually. This is in contrast to the new method which just computes the SFs once at the start and then has the SFs go along for the ride a new entry in the `events` array. As a result I would like to get feedback and make sure everyone is aware of this new method for computing the lepton SFs.

The current list of action items that I would like to get feedback on are:

1. Discussion on the choice of function names, `AttachElectronSF` and `AttachMuonSF`. I don't really have a strong personal preference regarding these names and so I am open to changing them, so long as they are sufficiently descriptive of what they do. My choice of name capitalization here is to attempt keep consistency with the other function definitions in [corrections.py](https://github.com/TopEFT/topcoffea/blob/simplify-lepSF/topcoffea/modules/corrections.py)
2. Discussion on the placement of the strings that define the names that get inserted into 'event record', `sf_nom`, `sf_hi`, and `sf_lo` in the code. These strings are hard coded values that are _only_ specified in the new functions, which might end up getting buried going forward, making it unclear why/how these special keywords are being used in other parts of the code, e.g. in the processor. I'm open to suggestions for specifying these strings elsewhere, possibly in a more global context so that it can be made obvious what is and what isn't contained in the 'event record'
3. Discussion on the actual choice of names for the SFs.
    1. I don't have a strong preference for what name we actually choose. For the object level SF names, I went with the generic `sf_nom` since it should be made obvious by context what object this SF corresponds to, e.g. `electron.sf_nom` would imply it is the electron SF and so no additional description should be needed. This naming choice could potentially create a conflict in the future, if we end up including a new object level lepton SF, e.g. trigger efficiencies. However, I think in those cases, a suitable alternative name can be found that doesn't conflict with the naming chosen here
    2. My choice of `nom`, `hi`, and `lo` is mainly for aesthetic reasons. It keeps each string roughly the same length for more uniform and easier to read code. Other SF code uses different verbiage, e.g. [central, up, down](https://github.com/TopEFT/topcoffea/blob/simplify-lepSF/topcoffea/modules/corrections.py#L243-L245). I would like to get consensus on if I should change it to be consistent with this naming, or if people are fine with my choice
4. The last piece of feedback I would like is whether or not I should go through and do the actual replacement of switching from `GetLeptonSF` to the new implementation as a part of this PR or if it should be done as a separate PR.

 I should also point out that there are two commits called "Add simplified SF functions", 54afcdc and 404aae2. These commits are identical and are the result of me trying to merge in upstream changes made to the master branch resulting from PR #42. I don't believe this should cause any issues, but thought I would point it out.

### CODE REVIEW

**Comment by andrea21z** [comment]
Hi Andrew,

I like these functions and I think they simplify the previous ones a lot.

- With respect to the names you have chosen, I think they are fine, I have no preference. 
- The strategy of including the SFs in the `events` record is very useful, so I'm fine with it.
- iI my opinion, it would be best to replace these functions in the analysis and include all the changes in the same PR.

Thank you very much for the implementation and let me know if I can help you in any way.

**Review by andrea21z — APPROVED** [review]

**Comment by Andrew42** [comment]
I've tested the changes and fixed a discrepancy in the new implementation related to using the correct electron eta values for computing the SF. I've also switched the main `topeft.py` code over to the new implementation and cleaned up parts of the code associated with the old implementation.

The PR should now be ready to merge into master assuming everyone is fine with the changes.

**Comment by klannon** [comment]
Do you know how easy it will be to merge this with the [EventSelection](https://github.com/TopEFT/topcoffea/tree/EventSelection) branch?  These are both important changes to merge in, but I'd hate to make it a lot harder to merge in EventSelection by merging this first.  One way to test this would be to checkout out this branch in your local area and try running a merge command to merge in Event selection.  If this generates a lot of tricky conflicts that need to be resolved, then we'll want to be careful.

Can you edit the PR name to remove the "[WIP]" tag?

**Comment by Andrew42** [comment]
@klannon looking over #45 it appears that my changes here shouldn't be too hard to pull into the `EventSelection` branch. The most important thing would be to make sure that when we add the `lepSF_nom`, `lepSF_hi`, and `lepSF_lo` to the `events` collection that it occurs _after_ all the of the object level cuts have been applied and non-analysis quality objects removed from the `e` and `mu` collections. Otherwise the following lines would include lepton SFs from leptons that don't actually enter the event selection:
```python
leps = ak.concatenate([e,mu],axis=-1)
nLeps = ak.num(leps)
events['lepSF_nom'] = ak.prod(leps.sf_nom,axis=-1)
events['lepSF_hi']  = ak.prod(leps.sf_hi,axis=-1)
events['lepSF_lo']  = ak.prod(leps.sf_lo,axis=-1)
```

**Comment by kmohrman** [comment]
@Andrew42, I checked out this branch and tried running over a central sample and an EFT sample, with futures and with wq, and can verify that it at least does not crash for me. Looking at where the changes to `topeft` occur, I agree that there is not a huge amount of overlap with the `EventSelection` branch, so hopefully it will not be too problematic to merge this branch first. However, I have not looked very closely at the content of the changes to `topeft`. I'm wondering if someone who has been working on the SFs (e.g. @andrea21z) could take a look through that before we move forward with merging?

**Review by andrea21z — APPROVED** [review]

**Pull request merged**
