### PR TITLE
Conda timeout

### PR DESCRIPTION
**Pull request by bryates**
Trying a timeout of 30 minutes when creating the conda environment.

### CODE REVIEW

**Comment by bryates** [comment]
I didn't realize my last push _did_ work. I'm rerunning the CI just to see if it works the first time. If so, then maybe we can merge this as well.

**Comment by kmohrman** [comment]
Great! I agree this might be easier to do for now, i.e. easier than switching everything to mamba (though I still agree we should still consider moving to mamba in the future).

I've just looked at the code, and I am wondering if you know if the fix was due to the timeout line or the swap space edits? Might be good to understand that before merging.

**Comment by bryates** [comment]
> Great! I agree this might be easier to do for now, i.e. easier than switching everything to mamba (though I still agree we should still consider moving to mamba in the future).
> 
> I've just looked at the code, and I am wondering if you know if the fix was due to the timeout line or the swap space edits? Might be good to understand that before merging.

I think the swap space was what finally did it.

**Comment by kmohrman** [comment]
Ok, good to know. So could we remove the `timeout-minutes: 30`?

**Comment by bryates** [comment]
> Ok, good to know. So could we remove the `timeout-minutes: 30`?

Sure, I've removed it.

**Pull request merged**
