### PR TITLE
Update xsec name

### PR DESCRIPTION
**Pull request by kmohrman**
Update a name of one of the cross sections (not used in TOP-22-006).

### CODE REVIEW

**Review by bryates — APPROVED** [review]
Thanks @kmohrman, looks good to me!

**Comment by bryates** [comment]
> Thanks @kmohrman, looks good to me!

I still haven't figured out why conda times out in the CI, but this should be safe to merge.

**Comment by kmohrman** [comment]
Thanks, I've added one more xsec. Should I go ahead and merge? The CI should pass on the master branch since your PR #11 is merged.

**Comment by bryates** [comment]
> Thanks, I've added one more xsec. Should I go ahead and merge? The CI should pass on the master branch since your PR #11 is merged.

Sure, go ahead and merge.

**Pull request merged**
