### PR TITLE
Update skims for data samples using NAOD v9

### PR DESCRIPTION
**Pull request by Andrew42**
This PR updates and makes available skims for the Run 2 datasets using NAODv9. It follows the same procedure and setup as in PR #129. It updates the json making script to produce the json files for the NAODv9 data and replaces the old data jsons with the new ones. These jsons were then used to produce the skimmed datasets using the [LobsterSkimming](https://github.com/TopEFT/LobsterSkimming) code.

Once the skims were produced, jsons for these samples were made by running the following command from the `topcoffea/analysis/topEFT` directory:
```
python make_skim_jsons.py --json-dir ../../topcoffea/json/data_samples --file ND_data_skim_locations.txt
```
Which uses an updated version of the `ND_data_skim_locations.txt` file, also included in this PR.

The new jsons (skimmed and un-skimmed) fully replace the previous ones and any old files have been completely removed. This is due to fact that naming for a few of the 2016 run eras has changed w.r.t. the NAODv8 versions. The changes are the following:
```
*_C-UL2016 -> *_C-HIPM_UL2016
*_D-UL2016 -> *_D-HIPM_UL2016
*_E-UL2016 -> *_E-HIPM_UL2016
```
By fully removing the old data jsons we ensure that there aren't any stray json files pointing to old NAODv8 data lying around. In any case, the `data_samples_NDSkim.cfg` and `data_samples.cfg` files have both been updated to reflect the new naming and should point to the correct json file locations.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks very much @Andrew42 for this PR. I've added @abasnet97 as a reviewer, as he's been working on doing some validation of the skims, but was running into lots of issues with the old v8 samples not being available anymore. So, @abasnet97, I think it'd be great if you could try running the new v9 samples that Andrew has added JSONs for (both the skimmed and unskimmed) in order to do the comparisons we talked about. 

(Also linking Issue #135 to this PR  for reference.)

**Comment by abasnet97** [comment]
Hi @kmohrman, I will do it this afternoon. Thanks @Andrew42 for the update.

**Review by bryates — APPROVED** [review]
Everything looks good to me, and with @abasnet97's checks, I think this PR is good to go. This closes #135.

**Comment by kmohrman** [comment]
This looks good to me as well. I think that as soon as @abasnet97 confirms the last question I had on Issue #135, we'll be ready to merge.

**Comment by Andrew42** [comment]
I just want to chime in here and say that @abasnet97 indicated to me that there may in fact be discrepancies between the skimmed and unskimmed samples he was comparing, so please hold off on merging this PR right away

**Comment by kmohrman** [comment]
I agree that we should hold off on merging for now. For reference, the potential discrepancies were discovered while @abasnet97 was investigating the last check requested on Issue #135 (so for additional discussion on this discrepancy, we might want to continue it on the issue instead of here, though the issue is already linked to this PR so maybe it does not really matter where we discuss the issue).

**Comment by Andrew42** [comment]
I've gone ahead and merged the changes introduced by PR #158. Since that branch was based off of master, it also back ports a large number of commits that have been made since this PR was originally opened. Only two trivial merge conflicts needed to be resolved related to `SingleElectron_D-UL2016.json` and `SingleElectron_D-UL2016_NDSkim.json`, which was introduced due to #153 (likely by accident). In any case these two files where to be removed and replaced as part of this PR anyways, so the merge conflict was trivial to resolve, but I figure should be mentioned just in case.

I've also update the `make_json.py` script to include the previously missing MuonEG dataset string for the 2016 data and also updated the corresponding `cfg` file.

Note: I have not (yet) made a skim of the missing MuonEG dataset, so the `*_NDSkim` variants of both the json and cfg files have not been updated. @abasnet97 you should make sure to keep this in mind when doing any additional skimmed vs. un-skimmed comparisons and should probably make sure to not include the 2016 MuonEG dataset in your un-skimmed results. At least until I've made and committed the skim for that dataset.

**Comment by kmohrman** [comment]
Hi all, as this PR has been open for quite some time, I propose that we consider merging it now. 

As pointed out above, merging this PR will not change any of the current code (it essentially just adds new skims). We had been holding off on merging, since we wanted to fully validate these skims before merging them. However, as it has now become apparent that the skims will need to be remade anyway, it might be good to get this preliminary version into the code before any merge conflicts have a chance to develop. Additionally, as @Andrew42 mentioned in Issue #161, a skimmed version of the 2016 MuonEG dataset has still not been produced, so that will need to be done at some point int the future as well (as another PR). Furthermore, as PR #158 ended up getting merged into both the master and into this branch, it might be good to get this branch now merged into the master just to make sure nothing gets messy. 

For these reasons, I'd vote for merging this PR now (with Issues #135 and #161 remaining open for now, to be eventually closed by subsequent PRs), and I'm interested in hearing @bryates's and @Andrew42's thoughts about this possible course of action.

**Comment by bryates** [comment]
> Hi all, as this PR has been open for quite some time, I propose that we consider merging it now.
> 
> As pointed out above, merging this PR will not change any of the current code (it essentially just adds new skims). We had been holding off on merging, since we wanted to fully validate these skims before merging them. However, as it has now become apparent that the skims will need to be remade anyway, it might be good to get this preliminary version into the code before any merge conflicts have a chance to develop. Additionally, as @Andrew42 mentioned in Issue #161, a skimmed version of the 2016 MuonEG dataset has still not been produced, so that will need to be done at some point int the future as well (as another PR). Furthermore, as PR #158 ended up getting merged into both the master and into this branch, it might be good to get this branch now merged into the master just to make sure nothing gets messy.
> 
> For these reasons, I'd vote for merging this PR now (with Issues #135 and #161 remaining open for now, to be eventually closed by subsequent PRs), and I'm interested in hearing @bryates's and @Andrew42's thoughts about this possible course of action.

I'm fine with closing the PR now, and following up with the issues later.

**Comment by kmohrman** [comment]
> > Hi all, as this PR has been open for quite some time, I propose that we consider merging it now.
> > As pointed out above, merging this PR will not change any of the current code (it essentially just adds new skims). We had been holding off on merging, since we wanted to fully validate these skims before merging them. However, as it has now become apparent that the skims will need to be remade anyway, it might be good to get this preliminary version into the code before any merge conflicts have a chance to develop. Additionally, as @Andrew42 mentioned in Issue #161, a skimmed version of the 2016 MuonEG dataset has still not been produced, so that will need to be done at some point int the future as well (as another PR). Furthermore, as PR #158 ended up getting merged into both the master and into this branch, it might be good to get this branch now merged into the master just to make sure nothing gets messy.
> > For these reasons, I'd vote for merging this PR now (with Issues #135 and #161 remaining open for now, to be eventually closed by subsequent PRs), and I'm interested in hearing @bryates's and @Andrew42's thoughts about this possible course of action.
> 
> I'm fine with closing the PR now, and following up with the issues later.

Thanks @bryates, though just to clarify, I was actually proposing that we should potentially consider merging the PR, not closing it.

**Comment by bryates** [comment]
> > > Hi all, as this PR has been open for quite some time, I propose that we consider merging it now.
> > > As pointed out above, merging this PR will not change any of the current code (it essentially just adds new skims). We had been holding off on merging, since we wanted to fully validate these skims before merging them. However, as it has now become apparent that the skims will need to be remade anyway, it might be good to get this preliminary version into the code before any merge conflicts have a chance to develop. Additionally, as @Andrew42 mentioned in Issue #161, a skimmed version of the 2016 MuonEG dataset has still not been produced, so that will need to be done at some point int the future as well (as another PR). Furthermore, as PR #158 ended up getting merged into both the master and into this branch, it might be good to get this branch now merged into the master just to make sure nothing gets messy.
> > > For these reasons, I'd vote for merging this PR now (with Issues #135 and #161 remaining open for now, to be eventually closed by subsequent PRs), and I'm interested in hearing @bryates's and @Andrew42's thoughts about this possible course of action.
> > 
> > 
> > I'm fine with closing the PR now, and following up with the issues later.
> 
> Thanks @bryates, though just to clarify, I was actually proposing that we should potentially consider merging the PR, not closing it.

Of course, my mind connected close with finish. Let's merge it.

**Comment by kmohrman** [comment]
> > > > Hi all, as this PR has been open for quite some time, I propose that we consider merging it now.
> > > > As pointed out above, merging this PR will not change any of the current code (it essentially just adds new skims). We had been holding off on merging, since we wanted to fully validate these skims before merging them. However, as it has now become apparent that the skims will need to be remade anyway, it might be good to get this preliminary version into the code before any merge conflicts have a chance to develop. Additionally, as @Andrew42 mentioned in Issue #161, a skimmed version of the 2016 MuonEG dataset has still not been produced, so that will need to be done at some point int the future as well (as another PR). Furthermore, as PR #158 ended up getting merged into both the master and into this branch, it might be good to get this branch now merged into the master just to make sure nothing gets messy.
> > > > For these reasons, I'd vote for merging this PR now (with Issues #135 and #161 remaining open for now, to be eventually closed by subsequent PRs), and I'm interested in hearing @bryates's and @Andrew42's thoughts about this possible course of action.
> > > 
> > > 
> > > I'm fine with closing the PR now, and following up with the issues later.
> > 
> > 
> > Thanks @bryates, though just to clarify, I was actually proposing that we should potentially consider merging the PR, not closing it.
> 
> Of course, my mind connected close with finish. Let's merge it.

Sounds good! Ok, unless @Andrew42 has any objections, let's go ahead and get it merged.

**Comment by Andrew42** [comment]
No objections from me

**Pull request merged**
