### PR TITLE
Fix ext samples

### PR DESCRIPTION
**Pull request by bryates**
This PR updates some samples (`topcoffea/json/background_samples/central_UL/UL16APV_WZZ.json`, `topcoffea/json/background_samples/central_UL/UL16APV_ZZZ.json`, `topcoffea/json/background_samples/central_UL/UL16_WZZ.json`, and `topcoffea/json/background_samples/central_UL/UL16_ZZZ.json`) to fold the extensions into the nominal json files.

### CODE REVIEW

**Comment by bryates** [comment]
> @bryates I think we will now need to rerun the sow processor (and the update JSON script) to update the sum of the up/down weights. Do you want me to do that, or did you already plan to do that?

I already took care of that. These should be completely up to date.

**Comment by kmohrman** [comment]
> > @bryates I think we will now need to rerun the sow processor (and the update JSON script) to update the sum of the up/down weights. Do you want me to do that, or did you already plan to do that?
> 
> I already took care of that. These should be completely up to date.

Ah, perfect, thanks! I think I was looking at the wrong commit, sorry.

**Comment by kmohrman** [comment]
Thanks for this PR @bryates. It looks good to me. If @Andrew42 can confirm that it covers the missing ones he noticed, I'd be happy for it to be merged.

**Comment by Andrew42** [comment]
Looks good to me

**Review by Andrew42 — APPROVED** [review]

**Pull request merged**
