### PR TITLE
Adding SFs, categories and systematics

### PR DESCRIPTION
**Pull request by GonzalezFJR**
Several updates, mostly in topeft.py
Charge split and 4l categories.
B-tagging SFs.
Uncertainties on plots. Lepton and b-tagging uncertainties.
Implemented JEC uncertainties (but not propagated to the categories, for the moment).

### CODE REVIEW

**Comment by bryates** [comment]
Closes #25

**Comment by kmohrman** [comment]
I think the new files in the data directory will not be included in the `topcoffea` package unless you specify them in the `setup.py` file. For example, to include the new `txt` files in `data/JEC/`, you would add `JEC/*.txt` to the `topcoffea` list in the `package_data` dictionary in the `setup.py` file.  

Since the files are not currently listed in the setup script, I think they're probably not being included as part of `topcoffea`. While this is not a problem when running locally with the `-e` option, I think would break if you installed without the `-e`, or if you tried to run with the work-queue version of the code. 

So, for these reasons, I think it might be good to specify those new data files in `setup.py` before merging. To make sure that they are being properly included, you could try uninstalling `topcoffea`, then reinstalling without the `-e` and check that it is able to find the files.

**Comment by GonzalezFJR** [comment]
> I think the new files in the data directory will not be included in the `topcoffea` package unless you specify them in the `setup.py` file. For example, to include the new `txt` files in `data/JEC/`, you would add `JEC/*.txt` to the `topcoffea` list in the `package_data` dictionary in the `setup.py` file.
> 
> Since the files are not currently listed in the setup script, I think they're probably not being included as part of `topcoffea`. While this is not a problem when running locally with the `-e` option, I think would break if you installed without the `-e`, or if you tried to run with the work-queue version of the code.
> 
> So, for these reasons, I think it might be good to specify those new data files in `setup.py` before merging. To make sure that they are being properly included, you could try uninstalling `topcoffea`, then reinstalling without the `-e` and check that it is able to find the files.

Thanks @kmohrman , I added those files to the setup.py script.

**Comment by bryates** [comment]
@GonzalezFJR is there anything left on this PR, or were you just waiting on @kmohrman and I to merge it?

**Comment by GonzalezFJR** [comment]
Yes @bryates I was waiting for you or @kmohrman to merge it when you're happy. I plan to create another PR to introduce the json-based file configs.

**Comment by kmohrman** [comment]
@GonzalezFJR, after the bug fix @bryates mentioned, and the fixes you already made for the `setup.py` script and the `MET_pt` issue, I think this PR looks good to me.

**Pull request merged**
