### PR TITLE
restrict remote_environment.py changes to topcoffea/ and setup.py

### PR DESCRIPTION
**Pull request by btovar**
Instead of listing paths to exclude, now we only check explicitly listed directories and files.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks for this update @btovar, it looks good to me. Before we merge, @Andrew42 I'm wondering if you could try out this branch just to verify that the updates work as expected in the case you were asking about yesterday (i.e. your changes in topcoffea/tests do not trigger a rebuild, but changes to topcoffea/topcoffea still do)?

**Review by bryates — APPROVED** [review]

**Comment by kmohrman** [comment]
> Thanks for this update @btovar, it looks good to me. Before we merge, @Andrew42 I'm wondering if you could try out this branch just to verify that the updates work as expected in the case you were asking about yesterday (i.e. your changes in topcoffea/tests do not trigger a rebuild, but changes to topcoffea/topcoffea still do)?

@Andrew42, just wondering if you had a chance to test this out?

**Comment by Andrew42** [comment]
I tried testing this new feature out, however, when I run on `earth` I get the following warning message:
```
WARNING:git version is older than 1.9.5, ignoring path restricitons when checking for changes: topcoffea,setup.py
```
And indeed when I tried to run the processor after modifying a file in [tests](https://github.com/TopEFT/topcoffea/tree/master/tests) it forced a rebuild of the environment. So I'm guessing this feature is just getting skipped b/c of the older `git` version?

**Comment by btovar** [comment]
Correct. You can conda install -c conda-forge git  in your topcoffea env to get an adequate version of git.

**Comment by kmohrman** [comment]
Also, thanks for testing this @Andrew42. Were there any other aspects of the PR that you wanted to test, or should we go ahead and merge it?

**Comment by Andrew42** [comment]
I'm fine with merging it

**Pull request merged**
