### PR TITLE
Cuts

### PR DESCRIPTION
**Pull request by kmohrman**
The main goal of this branch is to modify the categories in the histograms that are produced by the `topeft.py` processor to better match the categories from TOP-19-001. We have also added a script ([find_yields.py](https://github.com/TopEFT/topcoffea/blob/cuts/analysis/topEFT/find_yields.py)) that loads the histograms from the pkl file produced by `topeft.py` and finds the yields in the various categories from those histograms.

### CODE REVIEW

**Comment by kmohrman** [comment]
@bryates, I was looking through the diff, and am wondering if `plot.py` would need to be updated to account for the new `ch0` category? I'm not too familiar with that script, so I could just be missing something, but I wanted to point it out just in case.

**Comment by bryates** [comment]
> @bryates, I was looking through the diff, and am wondering if `plot.py` would need to be updated to account for the new `ch0` category? I'm not too familiar with that script, so I could just be missing something, but I wanted to point it out just in case.

The plot script is actually very robust. I added a few lines to make it plot all the categories
https://github.com/TopEFT/topcoffea/blob/47670d491d9e3daa14b77004f56ccb888ecff05d/analysis/topEFT/plot.py#L77-L160
and an improvement to the naming convention
https://github.com/TopEFT/topcoffea/blob/47670d491d9e3daa14b77004f56ccb888ecff05d/topcoffea/plotter/plotter.py#L292

**Comment by bryates** [comment]
I do need to add the rebin commands eventually. Not sure if this should hold up the PR.

**Comment by yanfr0818** [comment]
Thanks for the update. I have a few questions:
1. Do we need to include a category for the loose WP of btagDeepFlavB? I'm not sure if it's used anywhere.
2. I suggest merge the nbjet categories `['1+bm2+bl','1bm','2+bm']` into the `level` axis.

**Comment by bryates** [comment]
> Thanks for the update. I have a few questions:
> 
> 1. Do we need to include a category for the loose WP of btagDeepFlavB? I'm not sure if it's used anywhere.
> 2. I suggest merge the nbjet categories `['1+bm2+bl','1bm','2+bm']` into the `level` axis.

Yes, we do need them. We are trying to match Table 14 in the AN. I suppose we could put them in the `levels` category to reduce the number of categories we have. I'll look into that.

**Comment by yanfr0818** [comment]
> > Thanks for the update. I have a few questions:
> > 
> > 1. Do we need to include a category for the loose WP of btagDeepFlavB? I'm not sure if it's used anywhere.
> > 2. I suggest merge the nbjet categories `['1+bm2+bl','1bm','2+bm']` into the `level` axis.
> 
> Yes, we do need them. We are trying to match Table 14 in the AN. I suppose we could put them in the `levels` category to reduce the number of categories we have. I'll look into that.

I see. Table 14 has a jet requirement and a jet subcategories as well. We used to have something like `4j1b` and `4j2b` in `level`. Do we need to include something like that?

**Comment by bryates** [comment]
> > > Thanks for the update. I have a few questions:
> > > 
> > > 1. Do we need to include a category for the loose WP of btagDeepFlavB? I'm not sure if it's used anywhere.
> > > 2. I suggest merge the nbjet categories `['1+bm2+bl','1bm','2+bm']` into the `level` axis.
> > 
> > 
> > Yes, we do need them. We are trying to match Table 14 in the AN. I suppose we could put them in the `levels` category to reduce the number of categories we have. I'll look into that.
> 
> I see. Table 14 has a jet requirement and a jet subcategories as well. We used to have something like `4j1b` and `4j2b` in `level`. Do we need to include something like that?

I don't think I fully appreciated those categories when I removed them. We would still need something for the loose+medium, but I'll think a bit about it.

**Comment by bryates** [comment]
> > > > Thanks for the update. I have a few questions:
> > > > 
> > > > 1. Do we need to include a category for the loose WP of btagDeepFlavB? I'm not sure if it's used anywhere.
> > > > 2. I suggest merge the nbjet categories `['1+bm2+bl','1bm','2+bm']` into the `level` axis.
> > > 
> > > 
> > > Yes, we do need them. We are trying to match Table 14 in the AN. I suppose we could put them in the `levels` category to reduce the number of categories we have. I'll look into that.
> > 
> > 
> > I see. Table 14 has a jet requirement and a jet subcategories as well. We used to have something like `4j1b` and `4j2b` in `level`. Do we need to include something like that?
> 
> I don't think I fully appreciated those categories when I removed them. We would still need something for the loose+medium, but I'll think a bit about it.

I've settled on these changes, merging the `nbjet` category into the `levels` category
https://github.com/TopEFT/topcoffea/blob/d2faa9bf1c1e3c7c27b57a2461e891dbee909bf2/analysis/topEFT/topeft.py#L486-L490
I don't think we need to add the light jets cut here, since it will just increase the categories. We're currently using the rebin function to account for the histograms being larger than needed, at the analysis level:
```
if var == 'njets':
    if '2l' in chan: h_base = h_base.rebin('njets', hist.Bin("njets",  "Jet multiplicity ", [4,5,6,7]))
    elif '3l' in chan: h_base = h_base.rebin('njets', hist.Bin("njets",  "Jet multiplicity ", [2,3,4,5]))
    elif '4l' in chan: h_base = h_base.rebin('njets', hist.Bin("njets",  "Jet multiplicity ", [2,3,4]))
```
While this does require a bit more work at analysis level, I feel it keeps the analyzer as general as possible.

**Comment by kmohrman** [comment]
@bryates the update to put the bjet categories into `levels` looks good to me. I'm wondering if you tried rerunning to verify that we get the same yields (just to make sure we're not missing something)?

**Comment by bryates** [comment]
> @bryates the update to put the bjet categories into `levels` looks good to me. I'm wondering if you tried rerunning to verify that we get the same yields (just to make sure we're not missing something)?

Yes, I did run that check before pushing :-)

**Comment by kmohrman** [comment]
Thanks @bryates. I've adjusted `find_yields.py` to accommodate the change of the bjets categories to the `cut` axis as well.

**Comment by bryates** [comment]
> Thanks @bryates. I've adjusted `find_yields.py` to accommodate the change of the bjets categories to the `cut` axis as well.

Looks good! Is there anything else left, or should we merge this PR?

**Comment by kmohrman** [comment]
@bryates I think if we can confirm that someone else besides you and I have actually successfully run on this branch, then we would be ready to merge it. @yanfr0818, I'm wondering if you've had a chance to try out this branch with a test job?

**Comment by yanfr0818** [comment]
> @bryates I think if we can confirm that someone else besides you and I have actually successfully run on this branch, then we would be ready to merge it. @yanfr0818, I'm wondering if you've had a chance to try out this branch with a test job?

I tested with an mc2018 sample:
1. The main processor works as intended.
2. `plot.py` can run, but no plots produced in `./temp/` but `yields.tex` was produced.
3. I didn't try `find_yields.py`. It seems to work with only central or private UL18 samples.

**Comment by kmohrman** [comment]
> I tested with an mc2018 sample:
> 
> 1. The main processor works as intended.
> 2. `plot.py` can run, but no plots produced in `./temp/` but `yields.tex` was produced.
> 3. I didn't try `find_yields.py`. It seems to work with only central or private UL18 samples.

Thanks for taking a look at this @yanfr0818. I do have a question though, I'm not sure if I understand why you say that `find_yields.py` would only work for UL18 samples? I have actually been running with UL17 samples so far, but I think it should work for any of the years, as long as we have the luminosity for that year stored in the `topcoffea/json/lumi.json` file. I suppose we'd also have to edit the `PROC_MAP` to include the sample names for the different processes, but I think that should not be an issue. Sorry if I'm just missing something obvious.

**Comment by yanfr0818** [comment]
> > I tested with an mc2018 sample:
> > 
> > 1. The main processor works as intended.
> > 2. `plot.py` can run, but no plots produced in `./temp/` but `yields.tex` was produced.
> > 3. I didn't try `find_yields.py`. It seems to work with only central or private UL18 samples.
> 
> Thanks for taking a look at this @yanfr0818. I do have a question though, I'm not sure if I understand why you say that `find_yields.py` would only work for UL18 samples? I have actually been running with UL17 samples so far, but I think it should work for any of the years, as long as we have the luminosity for that year stored in the `topcoffea/json/lumi.json` file. I suppose we'd also have to edit the `PROC_MAP` to include the sample names for the different processes, but I think that should not be an issue. Sorry if I'm just missing something obvious.

Sorry, I meant UL17, not UL18. Because in the main function, it only handles the yields with UL17 central and private samples. Besides that, from what I've seen in the `PROC_MAP` dictionary, this script would only work if we use such naming parttern for the axis names, which means it enforces a requirement for the arguments of `createJSON.py`. I'm personally not using that naming partterns. We would need the right `make_jsons.py` script if we want to test it.

**Comment by kmohrman** [comment]
By the way, I've modified the wq run script to only specify 1 core per task (in `executor_args`) [here](https://github.com/TopEFT/topcoffea/commit/735c211203ce90c7bc21b5b54af1387bb9dfbeca), to address [Issue 37](https://github.com/TopEFT/topcoffea/issues/37). It's not really related to the `cuts` branch, but we'll want this to be applied to the master branch, so I pushed it here so it will be included when we merge.

**Comment by yanfr0818** [comment]
> > I tested with an mc2018 sample:
> > 
> > 1. The main processor works as intended.
> > 2. `plot.py` can run, but no plots produced in `./temp/` but `yields.tex` was produced.
> > 3. I didn't try `find_yields.py`. It seems to work with only central or private UL18 samples.
> 
> Thanks for taking a look at this @yanfr0818. I do have a question though, I'm not sure if I understand why you say that `find_yields.py` would only work for UL18 samples? I have actually been running with UL17 samples so far, but I think it should work for any of the years, as long as we have the luminosity for that year stored in the `topcoffea/json/lumi.json` file. I suppose we'd also have to edit the `PROC_MAP` to include the sample names for the different processes, but I think that should not be an issue. Sorry if I'm just missing something obvious.

Thanks for the clarification. It works for the mc2018 sample I tested with.
The other problem is about `PROC_MAP`. One has to manually change it according to the axis names of the pkl plot packages.
I'd prefer we name the axis the same way in central or private. Instead of assigning what we want to look at in `PROC_MAP`, the script would take all the processes exist in both pkl packages, and automatically substract the central with private to get the difference for each process.
For example, if we have the process `tttt`, the script would read `tttt` automatically without us adding `tttt` to `PROC_MAP`.

**Comment by kmohrman** [comment]
Thanks for the comments @yanfr0818. 

> I'd prefer we name the axis the same way in central or private.

For me, I'd actually prefer not to require that the central and private samples have the same names. If they have the same names, it makes them a bit harder to keep separated, (and also makes plotting them together a bit confusing since both have the same name in the legend). However, this PR does not actually change the axis names for any of the processes. They are specified in the json files, and were pushed as part of the json files PR. Just to make sure I'm understanding, you are suggesting that we change the names e.g. [here](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/json/signal_samples/private_UL/UL16APV_ttHJet_b1.json#L5)?  

> Instead of assigning what we want to look at in PROC_MAP, the script would take all the processes exist in both pkl packages, and automatically substract the central with private to get the difference for each process.

The code actually already does most of this. The idea is that you pass your histogram (that comes from the pkl) to `get_yld_dict()` and that will return a dictionary with the yields for all of the categories; the way the `PROC_MAP` is set up, you would indeed have to add a new entry if you were going to look at a new process that was not already included in the map, but you'd only have to do that once. After that, it would just automatically map the category name to the corresponding processes in the map. Once you have your yield dictionaries, you can compare them however you'd like, e.g. you could use the `get_pdiff_between_nested_dicts()` function to find the percent difference in all of the categories. If a process exists in one dictionary and not in the other, it just skips that process automatically.

I'm not sure if this answered your concernes or not, so please feel free to ask any followup questions you might have. I guess one other thing I should say is that `find_yields.py` is not at all a "finished product" at his point, but just a step towards the functionality we'll need in the future. We can always make updates and improvements in future branches, I just wanted to push what I have now mainly just to document how I was getting the yield numbers that I've been showing over the past week.

**Comment by yanfr0818** [comment]
> Thanks for the comments @yanfr0818.
> 
> > I'd prefer we name the axis the same way in central or private.
> 
> For me, I'd actually prefer not to require that the central and private samples have the same names. If they have the same names, it makes them a bit harder to keep separated, (and also makes plotting them together a bit confusing since both have the same name in the legend). However, this PR does not actually change the axis names for any of the processes. They are specified in the json files, and were pushed as part of the json files PR. Just to make sure I'm understanding, you are suggesting that we change the names e.g. [here](https://github.com/TopEFT/topcoffea/blob/master/topcoffea/json/signal_samples/private_UL/UL16APV_ttHJet_b1.json#L5)?
> 
> > Instead of assigning what we want to look at in PROC_MAP, the script would take all the processes exist in both pkl packages, and automatically substract the central with private to get the difference for each process.
> 
> The code actually already does most of this. The idea is that you pass your histogram (that comes from the pkl) to `get_yld_dict()` and that will return a dictionary with the yields for all of the categories; the way the `PROC_MAP` is set up, you would indeed have to add a new entry if you were going to look at a new process that was not already included in the map, but you'd only have to do that once. After that, it would just automatically map the category name to the corresponding processes in the map. Once you have your yield dictionaries, you can compare them however you'd like, e.g. you could use the `get_pdiff_between_nested_dicts()` function to find the percent difference in all of the categories. If a process exists in one dictionary and not in the other, it just skips that process automatically.
> 
> I'm not sure if this answered your concernes or not, so please feel free to ask any followup questions you might have. I guess one other thing I should say is that `find_yields.py` is not at all a "finished product" at his point, but just a step towards the functionality we'll need in the future. We can always make updates and improvements in future branches, I just wanted to push what I have now mainly just to document how I was getting the yield numbers that I've been showing over the past week.

I have one remaining question about the axis names of the processes. If I understand it correctly, `plot.py` requires the axis names to be something like `ZZTo2L2Nu` or `ZZTo2L2Q` in order to make the plots (like what @bryates commented earler today). That set of names are pretty different from the set of axis names specified in the json files, or the names in `PROC_MAP`. I assume we will make the naming of the processes axis consistent between `plot.py` and `find_yields.py` eventually?

**Comment by klannon** [comment]
I see a lot of discussion about how to use various scripts.  Can we have a README in the `analysis/topEFT` directory to explain the purpose of each of the scripts there and give some basic usage information?  (Did you know that you can put a README in any directory of a GH repository and it will be displayed when you go into that directory in GH?)  I think that will avoid some of the confusion that is natural when people are trying to learn how to use code that someone else wrote!

**Comment by bryates** [comment]
> I see a lot of discussion about how to use various scripts. Can we have a README in the `analysis/topEFT` directory to explain the purpose of each of the scripts there and give some basic usage information? (Did you know that you can put a README in any directory of a GH repository and it will be displayed when you go into that directory in GH?) I think that will avoid some of the confusion that is natural when people are trying to learn how to use code that someone else wrote!

That's a good idea. I'll make sure there's a README in the `analysis/topEFT` directory describing how to use `plot.py`.

**Comment by kmohrman** [comment]
> Can we have a README in the analysis/topEFT directory to explain the purpose of each of the scripts there and give some basic usage information?

Sounds good. I've added a [README](https://github.com/TopEFT/topcoffea/tree/cuts/analysis/topEFT) to that directory, and added info for `run.py`, `work_queue_run.py`, `find_yields.py`, and `make_jsons.py`. If everyone else could add some info for their scripts (I think that would be @bryates / @yanfr0818 for `plot.py`, @jlawrenc for `genPlot.py` and `Genrun.py`, @GonzalezFJR for `drawSliders.py`, and @bryates for `convert3lEFT.py`) that'd be great.

**Comment by kmohrman** [comment]
> I have one remaining question about the axis names of the processes. If I understand it correctly, plot.py requires the axis names to be something like ZZTo2L2Nu or ZZTo2L2Q in order to make the plots (like what @bryates commented earler today). That set of names are pretty different from the set of axis names specified in the json files, or the names in PROC_MAP. I assume we will make the naming of the processes axis consistent between plot.py and find_yields.py eventually?

Good point @yanfr0818, I agree that consistency is important. However, I'm not super familiar with the naming conventions in `plot.py` as I've never really used that script, so I'm not sure if I can answer your question. But @bryates would probably know? For `find_yields.py`, it assumes the names of the categories of the `sample` axis should match the `histAxisName` specified in the JSON, which I think should be consistent for all users, since we have the JSON files committed to the repository, so everyone should be using the same ones.

**Pull request merged**
