### PR TITLE
Clib Run3 JME

### PR DESCRIPTION
**Pull request by MatthewDittrich**
Removes the hard-coded jet algorithm 'AK4PFchs' which is used for Run 2 only. Run 3 uses AK4Puppi

Will require a slight change to the ApplyJetCorrections method in corrections.py of TopEFT.

Here is an example of the same method but in ewkcoffea: https://github.com/cmstas/ewkcoffea/blob/jec/ewkcoffea/modules/corrections.py#L446-L508 

I think the method for renaming the jec_types_clib could be used in TopEFT as well

### CODE REVIEW

**Comment by MatthewDittrich** [comment]
I have also updated on of the clib json files

**Review by bryates — COMMENTED** [review]
Thanks @MatthewDittrich, this looks pretty minimal. I'm guessing it won't affect Run 2 with the suggested change you left in the comments?

**Comment by MatthewDittrich** [comment]
> Thanks @MatthewDittrich, this looks pretty minimal. I'm guessing it won't affect Run 2 with the suggested change you left in the comments?

It will not affect the tool's handling for Run 2, but it will affect how the corrections should be passed into the CorrectedJetFactory.

**Comment by bryates** [comment]
> > Thanks @MatthewDittrich, this looks pretty minimal. I'm guessing it won't affect Run 2 with the suggested change you left in the comments?
> 
> It will not affect the tool's handling for Run 2, but it will affect how the corrections should be passed into the CorrectedJetFactory.

Ok thanks for clarifying. If @kmohrman doesn't have any comments, we an merge this PR.

**Review by bryates — APPROVED** [review]

**Comment by kmohrman** [comment]
It's fine for me. Is it also good with @anpicci?

**Comment by MatthewDittrich** [comment]
New change is a first pass at skipping the JER and uncertainties when data is handed to the CorrectedJetsFactory. This change adds a new boolean input parameter to the build method that is defaulted to false, but when set to true will skip unnecessary corrections

@anpicci also had an idea about skipping these if the JER and uncertainty lists are empty. Both are really good ideas to me and I have no preference

**Comment by anpicci** [comment]
@bryates @MatthewDittrich @kmohrman To me, it sounds good, no particular objection to this proposal. Have you cross-checked that this modification does not induce any changes in the analysis workflow for MC samples?

**Comment by MatthewDittrich** [comment]
> @bryates @MatthewDittrich @kmohrman To me, it sounds good, no particular objection to this proposal. Have you cross-checked that this modification does not induce any changes in the analysis workflow for MC samples?

Yes, I have verified this does not change MC

**Comment by kmohrman** [comment]
Ok, great. So, if there are no further comments on the PR, should we go ahead and merge?

**Comment by bryates** [comment]
> Ok, great. So, if there are no further comments on the PR, should we go ahead and merge?

No objections from me.

**Comment by kmohrman** [comment]
Ok, great. Since all questions have been answered and there are no further objections, I'll go ahead and merge.

**Pull request merged**
