### PR TITLE
Uncorrelated uncertainties

### PR DESCRIPTION
**Pull request by andrea21z**
Updating uncorrealted uncertainties with _{year} in the name:
- Trigger
- JER

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks very much for the PR @andrea21z! @bryates, will this require any changes in the datacard maker to handle these uncorrelated systematics? Or, since they're in the same format as the other uncorrelated shape systematics, will they be handled correctly automatically? Should we do a check before merging to make sure the templates look as we would expect?

**Comment by bryates** [comment]
> Thanks very much for the PR @andrea21z! @bryates, will this require any changes in the datacard maker to handle these uncorrelated systematics? Or, since they're in the same format as the other uncorrelated shape systematics, will they be handled correctly automatically? Should we do a check before merging to make sure the templates look as we would expect?

I believe it will be handled automatically.

**Comment by kmohrman** [comment]
> > Thanks very much for the PR @andrea21z! @bryates, will this require any changes in the datacard maker to handle these uncorrelated systematics? Or, since they're in the same format as the other uncorrelated shape systematics, will they be handled correctly automatically? Should we do a check before merging to make sure the templates look as we would expect?
> 
> I believe it will be handled automatically.

Ok, sounds good. So then I think just to double check this, we'd want to do the following:
* Make a pkl file that include the newly uncorrelated uncertainties (could run with all systematics included, or could comment out most of the others to keep the pkl file smaller). I think we'd only need one sample, but I think we'd need all 4 years of it. 
* Run the pkl file through the datacard maker
* Run the `parse_datacard_templtes.py` script on the output templates, and check that the nominal and up and down uncertainties look as expected.

@bryates or @andrea21z, could you run this check if you have time? If you don't have time, I can try to do it at some point.

**Comment by kmohrman** [comment]
> > > Thanks very much for the PR @andrea21z! @bryates, will this require any changes in the datacard maker to handle these uncorrelated systematics? Or, since they're in the same format as the other uncorrelated shape systematics, will they be handled correctly automatically? Should we do a check before merging to make sure the templates look as we would expect?
> > 
> > 
> > I believe it will be handled automatically.
> 
> Ok, sounds good. So then I think just to double check this, we'd want to do the following:
> 
> * Make a pkl file that include the newly uncorrelated uncertainties (could run with all systematics included, or could comment out most of the others to keep the pkl file smaller). I think we'd only need one sample, but I think we'd need all 4 years of it.
> * Run the pkl file through the datacard maker
> * Run the `parse_datacard_templtes.py` script on the output templates, and check that the nominal and up and down uncertainties look as expected.
> 
> @bryates or @andrea21z, could you run this check if you have time? If you don't have time, I can try to do it at some point.

@bryates or @andrea21z, just wondering if you've had a chance to look into this check?

**Comment by bryates** [comment]
> > > > Thanks very much for the PR @andrea21z! @bryates, will this require any changes in the datacard maker to handle these uncorrelated systematics? Or, since they're in the same format as the other uncorrelated shape systematics, will they be handled correctly automatically? Should we do a check before merging to make sure the templates look as we would expect?
> > > 
> > > 
> > > I believe it will be handled automatically.
> > 
> > 
> > Ok, sounds good. So then I think just to double check this, we'd want to do the following:
> > 
> > * Make a pkl file that include the newly uncorrelated uncertainties (could run with all systematics included, or could comment out most of the others to keep the pkl file smaller). I think we'd only need one sample, but I think we'd need all 4 years of it.
> > * Run the pkl file through the datacard maker
> > * Run the `parse_datacard_templtes.py` script on the output templates, and check that the nominal and up and down uncertainties look as expected.
> > 
> > @bryates or @andrea21z, could you run this check if you have time? If you don't have time, I can try to do it at some point.
> 
> @bryates or @andrea21z, just wondering if you've had a chance to look into this check?

Sorry, I guess I missed the last comment where you asked if I could take a look. I'll make a `pkl` file now, and try to run the rest.

**Comment by bryates** [comment]
I've made a full set of plots [here](https://www.crc.nd.edu/~byates2/coffea/ttlnu/) showing the shifts in the uncorrelated trigger systematics are very small. We should be good to merge now.

**Comment by kmohrman** [comment]
Great, thanks for the check @bryates, I'll go ahead and merge now.

**Pull request merged**
