### PR TITLE
Fix bugs in handling of sumw2

### PR DESCRIPTION
**Pull request by klannon**
Thanks to @btovar, I was able to isolate two bugs in HistEFT:
 1. In some cases, adding a HistEFT with no EFT weights to one with EFT weight would result in the `_sumw` values being erroneously copied into the `_sumw2` array of the sparse bin with EFT weights.
 2. Filling a non-EFT sparse bin when `_sumw2 = None` resulted in the coffea `Hist._init_sumw2()` being called instead of `HistEFT._init_sum2()`.

The good news is that if you've never noticed these bugs, then they're irrelevant to you, because if you'd ever triggered on, it would result in a crash.  (That's what @btovar was seeing.)  In fact, I'm 99% sure that it's almost impossible to trigger (2) above the way our code was written, so fixing it didn't actually address @btovar's crash.  That required (1) which I actually figured out 2nd.

Anyway, I hope this can be expeditiously merged.  It only modifies `HistEFT.py` so it shouldn't interfere with the on-going event synchronization.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks @klannon, this sounds good to me. However, I have question about an error I saw while running a quick test on your branch. I was just running `run.py`, and using one private EFT sample, and one central sample. This did not happen when I tried only an EFT sample, or only a central sample. The traceback is here:
```
Traceback (most recent call last):
  File "run.py", line 159, in <module>
    output = processor.run_uproot_job(flist, treename=treename, processor_instance=processor_instance, executor=processor.futures_executor, executor_args={"schema": NanoAODSchema,'workers': nworkers, 'pre_workers': 1}, chunksize=chunksize, maxchunks=nchunks)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 1466, in run_uproot_job
    wrapped_out = executor(chunks, closure, None, **exe_args)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 791, in futures_executor
    return processwith(poolinstance)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 773, in processwith
    return accumulate(
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 91, in accumulate
    accum = add(accum, next(gen))
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 50, in add
    out[key] = add(a[key], b[key])
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 33, in add
    return operator.add(a, b)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 178, in __add__
    ret.add(other)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 285, in add
    self[key] += value
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 188, in __iadd__
    self.add(other)
  File "/afs/crc.nd.edu/user/k/kmohrman/coffea_dir/check_PRs/klannon_fix-histeft-bugs/topcoffea/topcoffea/modules/HistEFT.py", line 282, in add
    if self._sumw[key].shape != self._dense_shape:
KeyError: (<StringBin (ttHJet_privateUL17) instance at 0x7f1faabc1580>,)
```

**Comment by klannon** [comment]
Thanks @kmohrman!  So, you're saying I should change the title of this PR from "Fix bugs..." to "Introduce bugs..."  This should be relatively easy to fix.  Probably I need to bit the bullet and introduce a proper unit test for `HistEFT`.  In the meantime, if you get a chance, could you point me to the config that generates this crash as well as the chunksize and any other relevant details in case I need to try to reproduce this myself?

**Comment by kmohrman** [comment]
I think that probably any combination of private and central samples should work to reproduce the crash (I tried two and both crashed), but here's the contents of a cfg that produces the crash for me:
```
root://deepthought.crc.nd.edu/
../../topcoffea/json/signal_samples/private_UL/UL17_ttHJet_b1.json

root://ndcms.crc.nd.edu/
../../topcoffea/json/signal_samples/central_UL/UL17_ttHnobb.json
```

I was just running with the default chunk size of 100000. When I first noticed the crash, I was just running over only one chunk (to make the tests faster). But after that I also let it run over all the chunks and still saw the same crash, just took longer to get there (somewhere around 15 min).

**Comment by klannon** [comment]
@kmohrman: This most recent commit should have fixed the problem you reported.  Let me know if you spot anything else.

**Comment by kmohrman** [comment]
Thanks @klannon! I just tested it out and it runs for me. But before we merge it, I am wondering if you could potentially merge or rebase this branch against the master, just so I could double check if any of these changes affect the yields?

**Comment by klannon** [comment]
@kmohrman:  Sure.  I just merged.

**Comment by kmohrman** [comment]
Thanks, @klannon. Comparing to the yields from the master branch, the percent differences are on the order of e-16. 

I'd be happy to merge the PR at this point.

**Review by kmohrman — APPROVED** [review]

**Pull request merged**
