### PR TITLE
Fix BrokenProcessPool Error

### LINKED ISSUE #30: Crash with Futures Executor
Under some circumstances (certainly while running on my Mac laptop), the futures executor crashes with the following stack trace:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/klannon/cms/EFT/topcoffea/analysis/topEFT/run.py", line 79, in <module>
    output = processor.run_uproot_job(flist, treename=treename, processor_instance=processor_instance, executor=processor.futures_executor, executor_args={"schema": NanoAODSchema,'workers': nworkers, 'pre_workers': 1}, chunksize=chunksize, maxchunks=nchunks)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 1162, in run_uproot_job
    out = pre_executor(to_get, metadata_fetcher, out, **pre_args)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 635, in futures_executor
    return processwith(poolinstance)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 615, in processwith
    gen = _futures_handler({pool.submit(function, item) for item in items}, tailtimeout)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 615, in <setcomp>
    gen = _futures_handler({pool.submit(function, item) for item in items}, tailtimeout)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Preprocessing:   0%|                                                                                                              | 0/1 [00:08<?, ?file/s]
Traceback (most recent call last):
  File "./run.py", line 79, in <module>
    output = processor.run_uproot_job(flist, treename=treename, processor_instance=processor_instance, executor=processor.futures_executor, executor_args={"schema": NanoAODSchema,'workers': nworkers, 'pre_workers': 1}, chunksize=chunksize, maxchunks=nchunks)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 1162, in run_uproot_job
    out = pre_executor(to_get, metadata_fetcher, out, **pre_args)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 635, in futures_executor
    return processwith(poolinstance)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 617, in processwith
    return accumulate(
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 94, in accumulate
    accum = iadd(accum, next(gen))
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 86, in <genexpr>
    gen = (x for x in items if x is not None)
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/site-packages/coffea/processor/executor.py", line 186, in _futures_handler
    yield done.pop().result()
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/klannon/miniconda3/envs/coffea-070-env/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
The same code runs fine with the iterative executor.  This should not happen.

(I think I also know how to fix it.  PR in progress.)

### PR DESCRIPTION
**Pull request by klannon**
Fixes #30

I'm still not sure I understand why this only seem to effect some people some of the time, but thanks to Google, I have at least solved it on my laptop (MacOS) by including proper "guards" (e.g. `if __name__ == '__main__'`) the the run scripts.

(Also, I added a `year : 2018` entry to `topcoffea/cfg/2018` just so people looking at that example will see that it's needed (well until we get our fancy new `jsonFiles` branch merged!

### CODE REVIEW

**Comment by yanfr0818** [comment]
Unfortunately it doesn't fix the crush for me. Running with `run.py` still gives such error:
`concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

**Comment by klannon** [comment]
Bummer.  😕  Well, since it is a small change that **does** at least fix my crash, maybe we could still merge it?  I'll ask Brent, Xuan, or Kelci to review.  Can you create a new issue in Github where we can discuss your crash in more detail?  Just start by putting in the stack trace and details about the environment in which you're running (e.g. how did you install the code, from conda or some other way, where are you running, etc.)?

**Comment by bryates** [comment]
`if __name__ == '__main__'` is good to have, but only really needed if a file like `run.py` is imported by another module. 
@klannon did you look into the `freeze_support()` line your error suggested in #30?

**Comment by klannon** [comment]
I did not, but frankly, I'm not sure that would make sense.  There's no guarantee that `freeze_support()` would fix the problem or that it should be needed at all.  It's not mentioned in the coffea documentation, for example, nor do I find any issues in the Coffea GH.  If we tried this, we'd have to understand what it's doing and validate that it doesn't mess anything else up.  Or we could just add a line that is at worst unnecessary but otherwise totally harmless.  So, given that choice, I'd rather just add a `if __name__ == '__main__'` and move on.

**Comment by klannon** [comment]
FYI: this is the first hit when I Google `freeze_support`:
https://stackoverflow.com/questions/24374288/where-to-put-freeze-support-in-a-python-script

Basically say, just use `if __name__ == '__main__'`.

**Comment by kmohrman** [comment]
Looks good to me. However, since I've never encountered the error this commit fixes, I'm not sure my review is all that useful. But for whatever it's worth, I did try running the `run.py` script on your branch (for both a central and an EFT sample) and it ran fine for me.

**Comment by klannon** [comment]
So, given that this PR is harmless for most people and fixes a problem for me, can we merge it?

**Pull request merged**
