### PR TITLE
Fix weights

### PR DESCRIPTION
**Pull request by bryates**
Number of events now looks reasonable
http://www.crc.nd.edu/~byates2/coffea/jsonFiles/ttH_private_UL17_fixsum_objects_flat/njets.png

### CODE REVIEW

**Comment by bryates** [comment]
I'm not sure if counts should be scaled by `weights_one` like here
https://github.com/TopEFT/topcoffea/blob/c82ac132bc836870c07d2552b53d85ccb933b268/analysis/topEFT/topeft.py#L584
or `weights_flat` like all other variables. Using `weights_one`, `PrintYields()` in the plot function gives `ttH=39055.76`
where as the plot gives [~11](http://www.crc.nd.edu/~byates2/coffea/jsonFiles/ttH_private_UL17_fixsum_objects_flat/counts.png) events, and `weights_flat` gives `ttH=7643.76`. It might be something inside `PrintYields()` since neither of these are close.

**Comment by GonzalezFJR** [comment]
> `weights_flat`

If we want to use 'counts' to obtain the yields, we should used weights_flat there. Not sure why it's not working for you... probably something related to the PrintYields() function.

**Comment by bryates** [comment]
I did just come across these lines:
https://github.com/TopEFT/topcoffea/blob/3a6c6803b1ccaf4490cc24ce15ce74f019c26dde/topcoffea/modules/fileReader.py#L234-L237
which look like another flip. I should fix this, but does anyone know if this `Method #3` is actually used? It says for unskimmed files, but I think `Method #2` is currently the one that runs with our files.

**Comment by kmohrman** [comment]
@bryates, I tried out this branch just to double check that it runs for me, and did not have any issues running either the regular run script or the work queue run script. 

Also, I've regenerated the JSON files for the central samples (and pushed the updated files to this branch) so that the `nGenEvents` and `nSumOfWeights` will be correct, since they were previously flipped due to the bug that's now fixed in `GetAllInfoFromFile()` from `fileReader.py`. I did not regenerate the JSONs for our private samples, since if I'm understanding correctly, I don't think this should matter for our private samples, since as we've discussed previously it's not clear what `nGenEvents` and `nSumOfWeights` from the NAOD currently correspond to for the private samples and those values are not actually used for anything right now. But @bryates, if I'm mixed up on that, please let me know.

**Comment by bryates** [comment]
Just as a note, the `nGenEvents` and nSumOfWeights bug fix
https://github.com/TopEFT/topcoffea/blob/a565bbfddd7d44ca74d5c646cfe6b1bbdccca5c7/topcoffea/modules/fileReader.py#L232-L233
only applies to the central samples. The data and private samples use ones for `nGenEvents`
https://github.com/TopEFT/topcoffea/blob/fixWeights/analysis/topEFT/topeft.py#L419
and the sum of the weights are used at analysis level
https://github.com/TopEFT/topcoffea/blob/fixWeights/topcoffea/plotter/plotter.py#L185-L190

**Pull request merged**
