### PR TITLE
Fix for the HistEFT rebin method to preserve bin array shape

### PR DESCRIPTION
**Pull request by Andrew42**
Fixes a bug in `HistEFT` where if you call the `rebin()` method. Bins without an EFT parameterization were getting converted into a form as if they were meant to have an EFT parameterization. Basically 1D arrays were getting turned into 2D arrays. Below is a MRE that should better illustrate the point:
```python
from coffea.hist import StringBin, Cat, Bin
from topcoffea.modules.HistEFT import HistEFT

wcnames = ["ctG"]
h = HistEFT("Events",wcnames,Cat("sample","sample"),Bin("pt","pt",5,0,5))

coeffs = [
    [1,2,3],
]

h.fill(sample="EFT",pt=1.0,eft_coeff=coeffs)
h.fill(sample="EFT",pt=2.0,eft_coeff=coeffs)
h.fill(sample="EFT",pt=5.0,eft_coeff=coeffs)

h.fill(sample="SM",pt=1.0,eft_coeff=None)
h.fill(sample="SM",pt=2.0,eft_coeff=None)
h.fill(sample="SM",pt=5.0,eft_coeff=None)

new_edges = [0,3,5]
h_rebin = h.rebin("pt",Bin("pt","pt",new_edges))

print("-"*50)
print("- Before calling .rebin()")
print("-"*50)
for k,v in h._sumw.items():
    print(k); print(v);
print("")
print("-"*50)
print("- After calling .rebin()")
print("-"*50)
for k,v in h_rebin._sumw.items():
    print(k); print(v);
```
The fix was to make sure that shape of the dense axis is preserved during rebinning.

### CODE REVIEW

**Review by bryates — APPROVED** [review]
Thanks @Andrew42! Do you want to add your example code to the pytest scripts, or is it not worth repeatedly running a test on the rebin function?

**Comment by Andrew42** [comment]
> Thanks @Andrew42! Do you want to add your example code to the pytest scripts, or is it not worth repeatedly running a test on the rebin function?

My MRE isn't really a test. It would need to be modified to actually check for what goes wrong. I _guess_ you would just need to add a check to make sure the shapes of the arrays are what you expect them to be, but I don't have time to play around with it right now and make sure it actually tests what we want it to test.

**Comment by bryates** [comment]
> > Thanks @Andrew42! Do you want to add your example code to the pytest scripts, or is it not worth repeatedly running a test on the rebin function?
> 
> My MRE isn't really a test. It would need to be modified to actually check for what goes wrong. I _guess_ you would just need to add a check to make sure the shapes of the arrays are what you expect them to be, but I don't have time to play around with it right now and make sure it actually tests what we want it to test.

That's ok, it's not really _needed_.

**Comment by kmohrman** [comment]
Thanks very much @Andrew42. I'm happy to see that the CI is passing on this branch, as I guess that implies this bug at least does not affect anything we're testing with the CI. 

I'd be happy to merge it now, unless anyone else wants to look at it in more detail first.

**Pull request merged**
