### PR TITLE
Allow processor to actually run over real data

### PR DESCRIPTION
**Pull request by Andrew42**
The PR applies changes to [selections.py](topcoffea/modules/selection.py) to allow the code to run over actual data. In the current state, the code checks to see if an event has passed at least one of a set of hard coded trigger names. The issue here is that if the HLT menu that was used to collect those events in the first place did not have one of those trigger names, then it would cause a `KeyError` and crash the job.

My fix is to simply get the list of all triggers present from the ROOT file and then only check for triggers that are actually present in that list. I've also add a check for the case where none of the hard coded trigger names were found in the event record and raises an error for such a case, as this would likely indicate that you need to revisit your trigger selection choices.

I've also held off on including the json files that specify the LFNs of the dataset ROOT files as I think that can just be handled as a separate PR, where there can be more focused discussion on which NAOD version should be used.

### CODE REVIEW

**Comment by kmohrman** [comment]
Thanks @Andrew42 for this PR. It looks good to me. It should of course have no effect on the MC samples, but I double checked the yields anyway, and there were no significant differences (largest percent differences on the order of e-16). I am happy to merge the PR now unless@bryates or @yanfr0818 (or anyone else) has any comments.

**Comment by kmohrman** [comment]
Ah, one other thing, I would be in favor of removing [this TODO](https://github.com/TopEFT/topcoffea/pull/71/files#diff-81a14ca09a54fc01904a1773f3b47e8b8b68eed1793a1b5a0b80e4a7693cd86eR147). I think we should definitely keep this as an error, not a warning.

**Comment by bryates** [comment]
This one looks good to me. @kmohrman feel free to merge.

**Comment by Andrew42** [comment]
> Ah, one other thing, I would be in favor of removing [this TODO](https://github.com/TopEFT/topcoffea/pull/71/files#diff-81a14ca09a54fc01904a1773f3b47e8b8b68eed1793a1b5a0b80e4a7693cd86eR147). I think we should definitely keep this as an error, not a warning.

Done and committed

**Review by kmohrman — APPROVED** [review]

**Comment by Andrew42** [comment]
For bookkeeping purposes, PR #73 is where the jsons with the full 2016-2018 data ROOT files are being added

**Pull request merged**
