### PR TITLE
integration of correction-lib tools in the JME tools

### PR DESCRIPTION
**Pull request by anpicci**
Since my correction-lib implementation modifies a tool provided with the coffea package, I am putting the new version of CorrectedJetsFactory.py in topcoffea while waiting the coffea team to revise my PR against coffea official repo.

### CODE REVIEW

**Comment by bryates** [comment]
Thanks @anpicci! Can you please fix the Lint errors
https://github.com/TopEFT/topcoffea/actions/runs/10885966186/job/30204814522?pr=43#step:4:32

**Review by bryates — COMMENTED** [review]
Thanks @anpicci. Since this is a new file modeled after a central coffea file, I don't have any comments, other than did you do any validation on TopEFT yet?

**Comment by anpicci** [comment]
@bryates I provided some validations in the topeft PR

**Comment by bryates** [comment]
> @bryates I provided some validations in the topeft PR

Great! I'm happy with these tiny differences: O(e-10) in the yields and O(0.001) in the limits. Those all seem consistent with the random noise we've seen in the past.

**Review by bryates — APPROVED** [review]

**Comment by kmohrman** [comment]
I believe @MatthewDittrich has also independently cross tested this implementation against an alternative setup and obtained the same results, is that correct @MatthewDittrich?

@MatthewDittrich did you have any comments on @anpicci's implementation here before we would move forward with merging?

**Comment by MatthewDittrich** [comment]
I have implemented the JEC/JER corrections as well for ewkcoffea and I see that both methods are giving the same result.

**Comment by kmohrman** [comment]
Ok thanks @MatthewDittrich. Great to have the cross checks. Gives us a lot of confidence in the implementation. 

I am happy for this PR to be merged.

**Pull request merged**
